/*https://stackoverflow.com/questions/64469458/dockerfile-run-a-init-sql-file-for-setting-up-tables update karne pending!!!*/
CREATE TABLE consumertable (
    feature_id VARCHAR PRIMARY KEY,
    feature_type VARCHAR,
    longitude FLOAT,
    latitude FLOAT,
    depth FLOAT,
    mag FLOAT,
    place VARCHAR,
    time TIMESTAMP,
    updated TIMESTAMP,
    tz INTEGER,
    url VARCHAR,
    detail VARCHAR,
    felt INTEGER,
    cdi FLOAT,
    mmi FLOAT,
    alert VARCHAR,
    status VARCHAR,
    tsunami INTEGER,
    sig INTEGER,
    net VARCHAR,
    code VARCHAR,
    ids VARCHAR,
    sources VARCHAR,
    product_type VARCHAR,
    nst INTEGER,
    dmin FLOAT,
    rms FLOAT,
    gap FLOAT,
    magtype VARCHAR,
    type VARCHAR,
    title VARCHAR
);